---
version: '3.8'
services:
  serviceone:
    image: api-server:latest
    ports:
      - 3000:8181
    deploy:
      replicas: 3
  servicetwo:
    image: api-server:latest
    ports:
      - 3001:8181
    deploy:
      replicas: 2
...